### ISSUE TITLE
[(odoo 10] Error installation module Infogreffe connector

### ISSUE THREAD

**Issue by cmutz** [akretion/odoo-usability#51]
Hello,

Whej i try to install the module Infogreffe connector, I have his error 👍 

`Traceback (most recent call last):
  File "/opt/odoo/server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/server/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/server/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/server/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/server/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/server/odoo/addons/base/module/module.py", line 411, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/server/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/extra-addons/odoo_addons/smile_upgrade/models/registry.py", line 44, in new
    return native_new(db_name, force_demo, update_module=update_module)
  File "/opt/odoo/server/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/server/odoo/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/server/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/server/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/server/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/server/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/server/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/server/odoo/tools/convert.py", line 796, in parse
    self.parse(rec, mode)
  File "/opt/odoo/server/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/server/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/oca-addons/web/help_online/models/ir_model.py", line 32, in _update
    res_id=res_id)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_model.py", line 1229, in _update
    record = record.create(values)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_ui_view.py", line 362, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/odoo/oca-addons/connector-telephony/base_phone/models/base.py", line 31, in create
    return super(Base, self).create(vals)
  File "/opt/odoo/extra-addons/odoo_magento2_ept/models/backend/producer.py", line 57, in create
    record_id = create_original(self, vals)
  File "/opt/odoo/server/odoo/models.py", line 3830, in create
    self._fields[key].determine_inverse(record)
  File "/opt/odoo/server/odoo/fields.py", line 1041, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/server/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_ui_view.py", line 380, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/oca-addons/connector-telephony/base_phone/models/base.py", line 22, in write
    return super(Base, self).write(vals)
  File "/opt/odoo/extra-addons/odoo_magento2_ept/models/backend/producer.py", line 80, in write
    result = write_original(self, vals)
  File "/opt/odoo/server/odoo/models.py", line 3556, in write
    self._write(old_vals)
  File "/opt/odoo/server/odoo/models.py", line 3707, in _write
    self._validate_fields(vals)
  File "/opt/odoo/extra-addons/odoo_addons/smile_base/models/models.py", line 52, in _validate_fields
    raise ValidationError(name)
ParseError: "Le champ `infogreffe_profit` n'existe pas

Contexte de l'erreur :
Vue `infogreffe.partner.form`
[view_id: 2147, xml_id: n/a, model: res.partner, parent_id: 1512]
None" while parsing /opt/odoo/extra-addons/odoo-usability/l10n_fr_infogreffe_connector/partner_view.xml:11, near
<record id="view_partner_form" model="ir.ui.view">
    <field name="name">infogreffe.partner.form</field>
    <field name="model">res.partner</field>
    <field name="inherit_id" ref="l10n_fr_siret.view_partner_add"/>
    <field name="arch" type="xml">
        <xpath expr="//field[@name='company_registry']/../.." position="after">
            <group name="infogreffe" string="Infogreffe" attrs="{'invisible': [('is_company', '=', False)]}">
                <field name="infogreffe_date"/>
                <field name="infogreffe_turnover"/>
                <field name="infogreffe_profit"/>
                <field name="infogreffe_headcount"/>
                <button colspan="2" string="Update from Infogreffe" name="button_get_from_infogreffe" type="object"/>
            </group>
        </xpath>
    </field>
</record>`

Can help me ?

Regards,

Clément

**Comment by kevpop** [comment]
I have the same error ! 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 411, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 796, in parse
    self.parse(rec, mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1229, in _update
    record = record.create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 362, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3831, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 1041, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 380, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3557, in write
    self._write(old_vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3708, in _write
    self._validate_fields(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1079, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Erreur lors de la validation de la contrainte

Le champ `infogreffe_headcount` n'existe pas

Contexte de l'erreur :
Vue `infogreffe.partner.form`
[view_id: 578, xml_id: n/a, model: res.partner, parent_id: 576]
None" while parsing /usr/lib/python2.7/dist-packages/odoo/odoo-usability/l10n_fr_infogreffe_connector/partner_view.xml:11, near
<record id="view_partner_form" model="ir.ui.view">
    <field name="name">infogreffe.partner.form</field>
    <field name="model">res.partner</field>
    <field name="inherit_id" ref="l10n_fr_siret.view_partner_add"/>
    <field name="arch" type="xml">
        <xpath expr="//field[@name='company_registry']/../.." position="after">
            <group name="infogreffe" string="Infogreffe" attrs="{'invisible': [('is_company', '=', False)]}">
                <field name="infogreffe_date"/>
                <field name="infogreffe_turnover"/>
                <field name="infogreffe_profit"/>
                <field name="infogreffe_headcount"/>
                <button colspan="2" string="Update from Infogreffe" name="button_get_from_infogreffe" type="object"/>
            </group>
        </xpath>
    </field>
</record>

Can you help me ? 

Best regards.

**Comment by Dywen** [comment]
Same issue for me.
I have corrected the commented line in the __init.py__ . The module is installed but facing another problem:
TypeError: button_get_from_infogreffe() takes at least 4 arguments (2 given)

Any idea please?
